# Pandas

Pandas kütüphanesi veriyi analiz etmek için kullanılır. Veri bilimi projelerinde,veri okuma, veri ön işleme gibi adımlarda kullanılır.
Pandasta en çok kullanılan veri yapılar Series ve DataFrame yapılarıdır.

**Seriler**

Seriler bir tablodaki sütunlar gibidir. Bir boyutlu arraylerdir.

In [1]:
#pip install pandas

In [1]:
import pandas as pd

In [2]:
seri = pd.Series([12,47,34,66,50])
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [3]:
type(seri)

pandas.core.series.Series

In [4]:
#index bilgisi verir
seri.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
#serideki eleman sayısını verir
seri.size

5

In [6]:
#boyut bilgisi verir
seri.ndim

1

In [7]:
#değerlere array formunda  erişmek istersek values methodunu kullanabiliriz
seri.values

array([12, 47, 34, 66, 50], dtype=int64)

In [8]:
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [9]:
#fonksiyonun içine girilen değer kadar veriyi gösterir
seri.head(3)

0    12
1    47
2    34
dtype: int64

In [10]:
seri.tail(3)

2    34
3    66
4    50
dtype: int64

In [11]:
#serilerde de indexing ve slicing işlemlerini yapabiliyoruz
seri[0]

12

In [12]:
seri[2]

34

In [13]:
seri[3]

66

In [14]:
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [15]:
seri[0:2]

0    12
1    47
dtype: int64

In [16]:
seri[1:4]

1    47
2    34
3    66
dtype: int64

In [17]:
#indexleri değiştirebilir,isimlendirme yapabiliriz
seri2 = pd.Series([15,45,63,85,41],index=[1,8,5,3,6])
seri2

1    15
8    45
5    63
3    85
6    41
dtype: int64

In [18]:
seri2[1]

15

In [19]:
seri2[5]

63

In [20]:
seri3 = pd.Series([15,45,63,85,41],index=["a","b","c","d","e"])
seri3

a    15
b    45
c    63
d    85
e    41
dtype: int64

In [21]:
seri3.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [22]:
seri3["b"]

45

In [23]:
seri3["d"]

85

In [24]:
seri3["a":"d"]

a    15
b    45
c    63
d    85
dtype: int64

In [25]:
#sözlük üzerinden seri oluşturalım
sozluk = {"Ayşe":42,
          "Elif":27,
          "Fatma":36}
sozluk

{'Ayşe': 42, 'Elif': 27, 'Fatma': 36}

In [26]:
yeni_sozluk = pd.Series(sozluk)
yeni_sozluk

Ayşe     42
Elif     27
Fatma    36
dtype: int64

In [27]:
yeni_sozluk["Ayşe"]

42

In [31]:
#######################
import numpy as np
dizi = np.random.randint(50,size=6)
dizi

array([12, 19, 40, 25,  3,  4])

In [30]:
seri2 = pd.Series(dizi)
seri2

0    15
1    31
2    17
3    36
4    16
5     6
dtype: int32

In [32]:
seri2.index

RangeIndex(start=0, stop=6, step=1)

In [33]:
seri2.index = ["a","b","c","d","e","f"]

In [34]:
seri2

a    15
b    31
c    17
d    36
e    16
f     6
dtype: int32

In [37]:
seri2["b"]

31

In [35]:
seri2[["b","d"]]

b    31
d    36
dtype: int32

In [38]:
seri2[["a","c","f"]]

a    15
c    17
f     6
dtype: int32

In [39]:
seri2[["b","d"]] = 55
seri2

a    15
b    55
c    17
d    55
e    16
f     6
dtype: int32

**DataFrame**

In [40]:
pd.DataFrame(seri2)

0
a  15
b  55
c  17
d  55
e  16
f   6

In [41]:
pd.DataFrame(seri2,columns=["Sayılar"])

Sayılar
a       15
b       55
c       17
d       55
e       16
f        6

In [42]:
yeni_dizi=np.random.randint(25,size=12).reshape(4,3)
yeni_dizi

array([[24,  0,  8],
       [17, 19, 21],
       [ 8, 22, 20],
       [10, 23,  8]])

In [43]:
df = pd.DataFrame(yeni_dizi,columns=["col1","col2","col3"])
df

col1  col2  col3
0    24     0     8
1    17    19    21
2     8    22    20
3    10    23     8

In [44]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [45]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [46]:
df.columns=["1.Sütun","2.Sütun","3.Sütun"]
df

1.Sütun  2.Sütun  3.Sütun
0       24        0        8
1       17       19       21
2        8       22       20
3       10       23        8

In [47]:
#satır ve sütun bilgisi verir
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['1.Sütun', '2.Sütun', '3.Sütun'], dtype='object')]

In [48]:
df.ndim

2

In [49]:
df.shape

(4, 3)

In [50]:
df.values

array([[24,  0,  8],
       [17, 19, 21],
       [ 8, 22, 20],
       [10, 23,  8]])

In [54]:
#Bir sözlükten DataFrame oluşturalım
a = np.random.randint(10,size=5)
b = np.random.randint(10,size=5)
c = np.random.randint(10,size=5)
print(a)
print(b)
print(c)

[8 5 4 9 7]
[1 2 5 9 3]
[6 1 2 0 4]


In [55]:
sozluk2 = {"Col1":a,"Col2":b,"Col3":c}
sozluk2

{'Col1': array([8, 5, 4, 9, 7]),
 'Col2': array([1, 2, 5, 9, 3]),
 'Col3': array([6, 1, 2, 0, 4])}

In [56]:
data = pd.DataFrame(sozluk2)
data

Col1  Col2  Col3
0     8     1     6
1     5     2     1
2     4     5     2
3     9     9     0
4     7     3     4

In [57]:
data[0:3]

Col1  Col2  Col3
0     8     1     6
1     5     2     1
2     4     5     2

In [58]:
data[1:-1]

Col1  Col2  Col3
1     5     2     1
2     4     5     2
3     9     9     0

In [59]:
data[::2]

Col1  Col2  Col3
0     8     1     6
2     4     5     2
4     7     3     4

In [60]:
data[1:4][["Col1","Col3"]]

Col1  Col3
1     5     1
2     4     2
3     9     0

In [61]:
data[0:3]["Col2"]

0    1
1    2
2    5
Name: Col2, dtype: int32

In [62]:
data[0:3][["Col2"]]

Col2
0     1
1     2
2     5

In [63]:
data[["Col1","Col3"]]

Col1  Col3
0     8     6
1     5     1
2     4     2
3     9     0
4     7     4

In [64]:
data[["Col2"]]

Col2
0     1
1     2
2     5
3     9
4     3

In [65]:
#Silme işlemi için drop kullanılır.
data

Col1  Col2  Col3
0     8     1     6
1     5     2     1
2     4     5     2
3     9     9     0
4     7     3     4

In [66]:
data.drop(1,axis=0)

Col1  Col2  Col3
0     8     1     6
2     4     5     2
3     9     9     0
4     7     3     4

In [67]:
data

Col1  Col2  Col3
0     8     1     6
1     5     2     1
2     4     5     2
3     9     9     0
4     7     3     4

In [68]:
#İşlemin kalıcı olması için inplace True yapılmalı
data.drop(1,axis=0,inplace=True)

In [69]:
data

Col1  Col2  Col3
0     8     1     6
2     4     5     2
3     9     9     0
4     7     3     4

In [70]:
new_data = data.drop("Col2",axis=1)
new_data

Col1  Col3
0     8     6
2     4     2
3     9     0
4     7     4

In [71]:
data

Col1  Col2  Col3
0     8     1     6
2     4     5     2
3     9     9     0
4     7     3     4

In [72]:
#Yeni bir sütun eklemek
data["Col4"] = data["Col1"]/data["Col2"]
data

Col1  Col2  Col3      Col4
0     8     1     6  8.000000
2     4     5     2  0.800000
3     9     9     0  1.000000
4     7     3     4  2.333333

In [73]:
seri2

a    15
b    55
c    17
d    55
e    16
f     6
dtype: int32

In [74]:
data2=pd.DataFrame(seri2)
data2

0
a  15
b  55
c  17
d  55
e  16
f   6

**Değişken Seçimi: loc & iloc**

**loc:** Etikete dayalı seçme işlemi gerçekleştirir. Seçmek istediğimiz satır ve sütunun adını belirtmek gerekir. Seçimlerde verilen aralığın son elemanını içerir.

[satır_adı,sütun_adı]

**iloc:** İndexe dayalı seçme işlemidir. Seçmek istenilen satur ve sütunun indexi belirtilir. Indexe dayalı bir yöntem olduğundan belirtilen aralığın son öğesini içermez.

[satır_indexi,sütun_indexi]

In [75]:
numbers = np.random.randint(40,size=(10,3))
numbers

array([[26, 22, 22],
       [21, 25, 14],
       [16, 39,  7],
       [ 6,  5, 30],
       [32, 25, 19],
       [12, 18, 33],
       [26, 30, 29],
       [28, 24, 35],
       [34, 34,  1],
       [39, 22, 14]])

In [76]:
df = pd.DataFrame(numbers,columns=["Col1","Col2","Col3"])
df

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [77]:
df.loc[0,"Col3"]

22

In [78]:
df.iloc[0,2]

22

In [79]:
df.loc[6,"Col2"]

30

In [80]:
df.iloc[6,1]

30

In [81]:
df

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [82]:
df.loc[2:8,"Col2":"Col3"]

Col2  Col3
2    39     7
3     5    30
4    25    19
5    18    33
6    30    29
7    24    35
8    34     1

In [83]:
df.iloc[2:9,1:3]

Col2  Col3
2    39     7
3     5    30
4    25    19
5    18    33
6    30    29
7    24    35
8    34     1

In [84]:
df.loc[0:5]

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33

In [85]:
df.loc[2:7]

Col1  Col2  Col3
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35

In [86]:
df.loc[2:7,"Col2"]

2    39
3     5
4    25
5    18
6    30
7    24
Name: Col2, dtype: int32

In [ ]:
#########

In [87]:
df

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [88]:
df["Col1"]

0    26
1    21
2    16
3     6
4    32
5    12
6    26
7    28
8    34
9    39
Name: Col1, dtype: int32

In [89]:
df["Col1"]>20

0     True
1     True
2    False
3    False
4     True
5    False
6     True
7     True
8     True
9     True
Name: Col1, dtype: bool

In [90]:
df[df["Col1"]>20]

Col1  Col2  Col3
0    26    22    22
1    21    25    14
4    32    25    19
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [91]:
df[df["Col1"]>20][["Col1"]]

Col1
0    26
1    21
4    32
6    26
7    28
8    34
9    39

In [92]:
df

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [93]:
df[df["Col3"]<30]

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
4    32    25    19
6    26    30    29
8    34    34     1
9    39    22    14

In [94]:
df[df["Col3"]<30][["Col3"]]

Col3
0    22
1    14
2     7
4    19
6    29
8     1
9    14

In [95]:
df[df["Col3"]<30][["Col2","Col3"]]

Col2  Col3
0    22    22
1    25    14
2    39     7
4    25    19
6    30    29
8    34     1
9    22    14

In [96]:
df

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [97]:
df[(df["Col2"]>20) & (df["Col3"]<30)]

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
4    32    25    19
6    26    30    29
8    34    34     1
9    39    22    14

In [98]:
df.Col1

0    26
1    21
2    16
3     6
4    32
5    12
6    26
7    28
8    34
9    39
Name: Col1, dtype: int32

In [101]:
df["Col1"]

0    26
1    21
2    16
3     6
4    32
5    12
6    26
7    28
8    34
9    39
Name: Col1, dtype: int32

In [100]:
df[df.Col1 > 15]

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
4    32    25    19
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [102]:
#join ile birleştirme işlemi yapılır
df

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [103]:
df2 = df+50
df2

Col1  Col2  Col3
0    76    72    72
1    71    75    64
2    66    89    57
3    56    55    80
4    82    75    69
5    62    68    83
6    76    80    79
7    78    74    85
8    84    84    51
9    89    72    64

In [104]:
pd.concat([df,df2])

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14
0    76    72    72
1    71    75    64
2    66    89    57
3    56    55    80
4    82    75    69
5    62    68    83
6    76    80    79
7    78    74    85
8    84    84    51
9    89    72    64

In [105]:
pd.concat([df,df2],ignore_index=True)

Col1  Col2  Col3
0     26    22    22
1     21    25    14
2     16    39     7
3      6     5    30
4     32    25    19
5     12    18    33
6     26    30    29
7     28    24    35
8     34    34     1
9     39    22    14
10    76    72    72
11    71    75    64
12    66    89    57
13    56    55    80
14    82    75    69
15    62    68    83
16    76    80    79
17    78    74    85
18    84    84    51
19    89    72    64

In [107]:
df

Col1  Col2  Col3
0    26    22    22
1    21    25    14
2    16    39     7
3     6     5    30
4    32    25    19
5    12    18    33
6    26    30    29
7    28    24    35
8    34    34     1
9    39    22    14

In [106]:
df2.columns=["Col1","Col2","Col4"]
df2

Col1  Col2  Col4
0    76    72    72
1    71    75    64
2    66    89    57
3    56    55    80
4    82    75    69
5    62    68    83
6    76    80    79
7    78    74    85
8    84    84    51
9    89    72    64

In [108]:
pd.concat([df,df2])

Col1  Col2  Col3  Col4
0    26    22  22.0   NaN
1    21    25  14.0   NaN
2    16    39   7.0   NaN
3     6     5  30.0   NaN
4    32    25  19.0   NaN
5    12    18  33.0   NaN
6    26    30  29.0   NaN
7    28    24  35.0   NaN
8    34    34   1.0   NaN
9    39    22  14.0   NaN
0    76    72   NaN  72.0
1    71    75   NaN  64.0
2    66    89   NaN  57.0
3    56    55   NaN  80.0
4    82    75   NaN  69.0
5    62    68   NaN  83.0
6    76    80   NaN  79.0
7    78    74   NaN  85.0
8    84    84   NaN  51.0
9    89    72   NaN  64.0

In [109]:
#ikisinde de ortak olan sütunları birleştirir
pd.concat([df,df2],join="inner")

Col1  Col2
0    26    22
1    21    25
2    16    39
3     6     5
4    32    25
5    12    18
6    26    30
7    28    24
8    34    34
9    39    22
0    76    72
1    71    75
2    66    89
3    56    55
4    82    75
5    62    68
6    76    80
7    78    74
8    84    84
9    89    72

In [110]:
pd.concat([df,df2],axis=1)

Col1  Col2  Col3  Col1  Col2  Col4
0    26    22    22    76    72    72
1    21    25    14    71    75    64
2    16    39     7    66    89    57
3     6     5    30    56    55    80
4    32    25    19    82    75    69
5    12    18    33    62    68    83
6    26    30    29    76    80    79
7    28    24    35    78    74    85
8    34    34     1    84    84    51
9    39    22    14    89    72    64

In [ ]:
####################

In [111]:
data = pd.DataFrame({"Öğrenciler":["Ayşe","Mehmet","Fatma","Fatma","Mehmet","Ayşe","Ayşe","Fatma","Mehmet"],
                   "Dersler":["Matematik","Türkçe","Türkçe","Fen Bilgisi","Matematik","Fen Bilgisi","Türkçe","Matematik","Fen Bilgisi"],
                    "Puan":[80,75,92,78,64,84,73,94,90]})

data

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
1     Mehmet       Türkçe    75
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
4     Mehmet    Matematik    64
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [112]:
data2 = pd.DataFrame({"Öğretmenler":["Selin","Furkan","Emine"],
                   "Dersler":["Matematik","Türkçe","Fen Bilgisi"]})
data2

Öğretmenler      Dersler
0       Selin    Matematik
1      Furkan       Türkçe
2       Emine  Fen Bilgisi

In [113]:
pd.merge(data,data2)

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [114]:
new_data = pd.merge(data,data2,on="Dersler")
new_data

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [115]:
data["Öğrenciler"]

0      Ayşe
1    Mehmet
2     Fatma
3     Fatma
4    Mehmet
5      Ayşe
6      Ayşe
7     Fatma
8    Mehmet
Name: Öğrenciler, dtype: object

In [116]:
data[["Öğrenciler"]]

Öğrenciler
0       Ayşe
1     Mehmet
2      Fatma
3      Fatma
4     Mehmet
5       Ayşe
6       Ayşe
7      Fatma
8     Mehmet

In [117]:
data

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
1     Mehmet       Türkçe    75
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
4     Mehmet    Matematik    64
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [118]:
#Ayşenin ders ve puanına bakalım
data[data["Öğrenciler"]=="Ayşe"]

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73

In [119]:
data[data["Öğrenciler"]=="Mehmet"]

Öğrenciler      Dersler  Puan
1     Mehmet       Türkçe    75
4     Mehmet    Matematik    64
8     Mehmet  Fen Bilgisi    90

In [120]:
data[data["Öğrenciler"]=="Fatma"]

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
7      Fatma    Matematik    94

In [121]:
data[data["Öğrenciler"]=="Mehmet"][["Dersler","Puan"]]

Dersler  Puan
1       Türkçe    75
4    Matematik    64
8  Fen Bilgisi    90

In [122]:
data[data["Dersler"]=="Matematik"]

Öğrenciler    Dersler  Puan
0       Ayşe  Matematik    80
4     Mehmet  Matematik    64
7      Fatma  Matematik    94

In [123]:
data[data["Dersler"]=="Fen Bilgisi"]

Öğrenciler      Dersler  Puan
3      Fatma  Fen Bilgisi    78
5       Ayşe  Fen Bilgisi    84
8     Mehmet  Fen Bilgisi    90

In [124]:
data[data["Dersler"]=="Fen Bilgisi"][["Öğrenciler","Puan"]]

Öğrenciler  Puan
3      Fatma    78
5       Ayşe    84
8     Mehmet    90

In [125]:
data[data["Puan"]>80]

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
5       Ayşe  Fen Bilgisi    84
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [126]:
data[(data["Dersler"] =="Matematik") & (data["Puan"]>80)]

Öğrenciler    Dersler  Puan
7      Fatma  Matematik    94

In [127]:
data[(data["Dersler"] =="Türkçe") & (data["Puan"]<85)]

Öğrenciler Dersler  Puan
1     Mehmet  Türkçe    75
6       Ayşe  Türkçe    73

In [129]:
data.columns

Index(['Öğrenciler', 'Dersler', 'Puan'], dtype='object')

In [130]:
data_sıralama = data[data["Puan"]>80]
data_sıralama

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
5       Ayşe  Fen Bilgisi    84
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [133]:
data_sıralama.sort_values(by="Puan",ascending=False)

Öğrenciler      Dersler  Puan
7      Fatma    Matematik    94
2      Fatma       Türkçe    92
8     Mehmet  Fen Bilgisi    90
5       Ayşe  Fen Bilgisi    84