# 1

Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

In [55]:
a = np.array([4,2,53,6,5,3])
print(a)
print(a.size)
np.shape(a)

[ 4  2 53  6  5  3]
6


(6,)

# 2
İki ve üç boyutlu arrayler oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapalım.

In [11]:
import numpy as np

In [36]:
b = np.array([[11,6,35,14,47],[2,7,3,15,45]])
print(b)
np.shape(b)

NameError: name 'array1' is not defined

In [38]:
b[1,2]

3

In [29]:
c = np.array([[[10,12,4],[2,5,20]],[[1,8,7],[5,5,4]]])
print(c)         
np.shape(c)

[[[10 12  4]
  [ 2  5 20]]

 [[ 1  8  7]
  [ 5  5  4]]]


(2, 2, 3)

In [46]:
c[1,1,1]

5

In [52]:
c[0,1,2]

20

# 3

Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturalım. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapalım.

In [65]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,20,45,31,23,9,4])
a = arr.reshape(3,6)
b = arr.reshape(2,3,3)
print("1 boyutlu dizi: \n",arr, "\n")
print("2 boyutlu dizi: \n",a,"\n")
print("3 boyutlu dizi: \n",b,"\n")

1 boyutlu dizi: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 20 45 31 23  9  4] 

2 boyutlu dizi: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [20 45 31 23  9  4]] 

3 boyutlu dizi: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [20 45 31]
  [23  9  4]]] 



In [69]:
b[0,1,:]

array([4, 5, 6])

In [70]:
a[2,:]

array([20, 45, 31, 23,  9,  4])

In [71]:
b[1,:,1]

array([11, 45,  9])

# 4

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [94]:
a = np.zeros((5,4),dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [93]:
b = np.ones((5,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# SIFIR MATRİSLERİ MATRİSLERLE BİRLEŞMEZ

In [98]:
np.concatenate([a,a ], axis =1)

array([[ 1,  2,  3,  4,  5,  6,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12],
       [20, 45, 31, 23,  9,  4, 20, 45, 31, 23,  9,  4]])

In [100]:
np.concatenate([a,a ], axis =0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [20, 45, 31, 23,  9,  4],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [20, 45, 31, 23,  9,  4]])

In [99]:
np.concatenate([b,b ], axis =1)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [102]:
np.concatenate([b,b ], axis =0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])